### ISSUE TITLE
Category tree

### ISSUE THREAD

**Issue by dkuep** [guaka/refugeewiki#1]
It would be helpful to organize content both by Location and by 'Activity' ~ the kind of service provided.
This is the current status, please comment on better ways to do it ;)

Location Tree could look like this:
**World >> Germany >> Hesse >> Gießen**
With Pages Linking to Category pages e.g. Page Hesse: #redirect [[Category:Hesse]]
"World" can be used as a start point to browse by location

Activity tree could look like this:
**Activity >> German Courses >> German Courses (Advanced Learners)**
Using "Activity" as top node, one generell Category ("German Courses") and one specific Sub-category ("German Courses (Advanced Learners)"). 

"Tags"
are currently used to organize different pages in a not yet developed fashion:
Category:Language Guide for online language guides e.g. Page:German - Arabic
Category:*Organization-Name* (e.g. Red Cross) to collect regional groups of larger organizations
Category:*Organization-Type* (e.g. Christian Organization) 
Category:How to help for Pages e.g. "How to help in Gießen" that contain information on where to donate etc.

**Comment by guaka** [comment]
I'm a fan of letting wikis grow organically. Only add categories when there's actually articles in those categories. It's fairly easy to adapt things later on if there aren't many categories.

**Comment by guaka** [comment]
http://refugeewiki.org/en/Special:AllPages
http://refugeewiki.org/en/Special:Categories

Looks like we have about as many articles as categories. I think articles should always largely outnumber categories for categories to remain useful.

**Comment by dkuep** [comment]
I took your advice and deleted many of the more wide categories.
